"""Add empresas table and update servidores with empresa_id

Revision ID: 3b2088759edd
Revises: da3d4a5997e0
Create Date: 2025-11-20 19:00:48.620530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b2088759edd'
down_revision: Union[str, None] = 'da3d4a5997e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=200), nullable=True),
    sa.Column('razon_social', sa.String(length=200), nullable=True),
    sa.Column('rut', sa.String(length=20), nullable=True),
    sa.Column('tipo_empresa', sa.String(length=50), nullable=True),
    sa.Column('industria', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('tamanio', sa.String(length=50), nullable=True),
    sa.Column('num_empleados', sa.Integer(), nullable=True),
    sa.Column('facturacion_anual', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('telefono_principal', sa.String(length=20), nullable=True),
    sa.Column('telefono_secundario', sa.String(length=20), nullable=True),
    sa.Column('email_principal', sa.String(length=255), nullable=True),
    sa.Column('email_facturacion', sa.String(length=255), nullable=True),
    sa.Column('sitio_web', sa.String(length=255), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('codigo_postal', sa.String(length=20), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('es_cliente', sa.Boolean(), nullable=False),
    sa.Column('es_proveedor', sa.Boolean(), nullable=False),
    sa.Column('es_partner', sa.Boolean(), nullable=False),
    sa.Column('fecha_inicio_relacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin_relacion', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_country_id'), 'empresas', ['country_id'], unique=False)
    op.create_index(op.f('ix_empresas_estado'), 'empresas', ['estado'], unique=False)
    op.create_index(op.f('ix_empresas_is_active'), 'empresas', ['is_active'], unique=False)
    op.create_index(op.f('ix_empresas_nombre'), 'empresas', ['nombre'], unique=False)
    op.create_index(op.f('ix_empresas_rut'), 'empresas', ['rut'], unique=True)
    op.add_column('servidores', sa.Column('empresa_id', sa.Integer(), nullable=True, comment='ID de la empresa propietaria del servidor'))
    op.create_index(op.f('ix_servidores_empresa_id'), 'servidores', ['empresa_id'], unique=False)
    op.create_foreign_key(None, 'servidores', 'empresas', ['empresa_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servidores', type_='foreignkey')
    op.drop_index(op.f('ix_servidores_empresa_id'), table_name='servidores')
    op.drop_column('servidores', 'empresa_id')
    op.drop_index(op.f('ix_empresas_rut'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_nombre'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_is_active'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_estado'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_country_id'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
