"""Add location tables and update leads with location fields

Revision ID: 3b2aea3cba82
Revises: c194aa8ee0f0
Create Date: 2025-11-20 12:08:26.775548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b2aea3cba82'
down_revision: Union[str, None] = 'c194aa8ee0f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('code3', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_es', sa.String(length=100), nullable=True),
    sa.Column('name_pt', sa.String(length=100), nullable=True),
    sa.Column('name_fr', sa.String(length=100), nullable=True),
    sa.Column('official_name', sa.String(length=200), nullable=True),
    sa.Column('phone_prefix', sa.String(length=10), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('continent', sa.String(length=50), nullable=False),
    sa.Column('subregion', sa.String(length=50), nullable=True),
    sa.Column('capital', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code3')
    )
    op.create_index(op.f('ix_countries_code'), 'countries', ['code'], unique=True)
    op.create_index(op.f('ix_countries_is_active'), 'countries', ['is_active'], unique=False)
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_ascii', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('capital', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'code', name='uq_state_country_code')
    )
    op.create_index(op.f('ix_states_country_id'), 'states', ['country_id'], unique=False)
    op.create_index(op.f('ix_states_is_active'), 'states', ['is_active'], unique=False)
    op.create_index(op.f('ix_states_name'), 'states', ['name'], unique=False)
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_ascii', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('is_capital', sa.Boolean(), nullable=False),
    sa.Column('is_national_capital', sa.Boolean(), nullable=False),
    sa.Column('is_major_city', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_country_id'), 'cities', ['country_id'], unique=False)
    op.create_index(op.f('ix_cities_is_active'), 'cities', ['is_active'], unique=False)
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=False)
    op.create_index(op.f('ix_cities_population'), 'cities', ['population'], unique=False)
    op.create_index(op.f('ix_cities_state_id'), 'cities', ['state_id'], unique=False)
    op.add_column('leads', sa.Column('country_id', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('state_id', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('city_id', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('leads', sa.Column('address_line1', sa.String(length=200), nullable=True))
    op.add_column('leads', sa.Column('address_line2', sa.String(length=200), nullable=True))
    op.add_column('leads', sa.Column('address_notes', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True))
    op.add_column('leads', sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True))
    op.add_column('leads', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_leads_city_id'), 'leads', ['city_id'], unique=False)
    op.create_index(op.f('ix_leads_country_id'), 'leads', ['country_id'], unique=False)
    op.create_index(op.f('ix_leads_state_id'), 'leads', ['state_id'], unique=False)
    op.create_foreign_key(None, 'leads', 'states', ['state_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'leads', 'cities', ['city_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'leads', 'countries', ['country_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_index(op.f('ix_leads_state_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_country_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_city_id'), table_name='leads')
    op.drop_column('leads', 'timezone')
    op.drop_column('leads', 'longitude')
    op.drop_column('leads', 'latitude')
    op.drop_column('leads', 'address_notes')
    op.drop_column('leads', 'address_line2')
    op.drop_column('leads', 'address_line1')
    op.drop_column('leads', 'postal_code')
    op.drop_column('leads', 'city_id')
    op.drop_column('leads', 'state_id')
    op.drop_column('leads', 'country_id')
    op.drop_index(op.f('ix_cities_state_id'), table_name='cities')
    op.drop_index(op.f('ix_cities_population'), table_name='cities')
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.drop_index(op.f('ix_cities_is_active'), table_name='cities')
    op.drop_index(op.f('ix_cities_country_id'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_states_name'), table_name='states')
    op.drop_index(op.f('ix_states_is_active'), table_name='states')
    op.drop_index(op.f('ix_states_country_id'), table_name='states')
    op.drop_table('states')
    op.drop_index(op.f('ix_countries_is_active'), table_name='countries')
    op.drop_index(op.f('ix_countries_code'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
