"""Add servidores table for iSeries infrastructure

Revision ID: da3d4a5997e0
Revises: 3b2aea3cba82
Create Date: 2025-11-20 12:50:41.550025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da3d4a5997e0'
down_revision: Union[str, None] = '3b2aea3cba82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servidores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_servidor', sa.String(length=100), nullable=True, comment='Nombre identificativo del servidor'),
    sa.Column('descripcion', sa.Text(), nullable=True, comment='Descripción o alias del servidor (Ej: Prod, Backup)'),
    sa.Column('modelo', sa.String(length=50), nullable=False, comment='Modelo del servidor (Ej: 9009-42A, 8203-E4A)'),
    sa.Column('processor_feature_code', sa.String(length=20), nullable=False, comment='Código de característica del procesador (Ej: EP30, EPX5)'),
    sa.Column('processor_tier', sa.Enum('P05', 'P10', 'P20', 'P30', 'P40', 'P50', 'UNKNOWN', name='processortier'), nullable=False, comment='Nivel de procesador (P05, P10, P20, P30)'),
    sa.Column('ubicacion', sa.String(length=200), nullable=True, comment='Ubicación física o lógica (Datacenter A, On-premise, Cloud)'),
    sa.Column('es_virtualizado', sa.Boolean(), nullable=False, comment='Indica si está virtualizado con PowerVM'),
    sa.Column('estado_registro', sa.Enum('PRELIMINAR', 'CONFIRMADO', 'REVISION', 'OBSOLETO', name='estadoregistro'), nullable=False, comment='Estado del registro (preliminar, confirmado)'),
    sa.Column('numero_serie', sa.String(length=50), nullable=True, comment='Número de serie del chasis'),
    sa.Column('machine_type', sa.String(length=20), nullable=True, comment='Tipo de máquina (Ej: 9009)'),
    sa.Column('frame_id', sa.String(length=50), nullable=True, comment='ID del frame si hay varios'),
    sa.Column('firmware_version', sa.String(length=50), nullable=True, comment='Versión del firmware'),
    sa.Column('cantidad_procesadores_fisicos', sa.Integer(), nullable=True, comment='Cantidad de procesadores físicos'),
    sa.Column('memoria_total_mb', sa.Integer(), nullable=True, comment='Memoria total en MB'),
    sa.Column('tipo_storage', sa.Enum('INTERNO', 'EXTERNO', 'SAN', 'NAS', 'VSAN', 'MIXTO', name='tipostorage'), nullable=True, comment='Tipo de almacenamiento'),
    sa.Column('os_version', sa.String(length=50), nullable=True, comment='Versión del OS/400 o IBM i (Ej: V7R4M0)'),
    sa.Column('ip_principal', sa.String(length=45), nullable=True, comment='Dirección IP principal'),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Indica si el servidor está activo'),
    sa.Column('notas', sa.Text(), nullable=True, comment='Notas adicionales o observaciones'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_serie')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servidores')
    # ### end Alembic commands ###
